# Use Python slim image
FROM python:3.11-slim

WORKDIR /app

# Copy requirements and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy only consumer code
COPY . .

# Default command to run the consumer
CMD ["python", "consumer.py"]
## docker-compose -f docker.yml build backend telemetry-consumer
#>> docker-compose -f docker.yml up -build