"""add is_read to alerts

Revision ID: f406f425bc9b
Revises: 98844573a2f9
Create Date: 2026-05-17 20:25:39.285004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f406f425bc9b'
down_revision: Union[str, Sequence[str], None] = '98844573a2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'UserDetails', ['user_name'])
    op.add_column('alerts', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'is_read')
    op.drop_constraint(None, 'UserDetails', type_='unique')
    # ### end Alembic commands ###
